title = "Simon Heimlicher"
copyright = "Copyright © Simon Heimlicher"

# set `baseurl` to your root domain including trailing slash
baseURL = "https://simon.heimlicher.com/"  # Include trailing slash

defaultContentLanguage = 'en'
languageCode = "en-us"

# https://gohugo.io/templates/robots/
enableRobotsTXT = true

ignoreFiles = [
  "\\.DS_Store$",
  "\\.vscode$",
  ".*\\.code-workspace$",
  "frontmatter\\.json$",
]

paginate = 20

###############################################################################
# NOTICE: After introducing the first section in TOML (e.g. "[Author]"),
# nothing is added to the root namespace
# No more changes to Hugo root-level configuration below this line

# https://discourse.gohugo.io/t/change-location-of-resources-directory/15682/3
# https://gohugo.io/getting-started/configuration/#configure-file-caches
# Avoid using resourceDir in the project directory
# Since resourceDir cannot be set from the command line or environment variables,
# we set it indirectly via --cacheDir or HUGO_CACHE_DIR
[caches]
  [caches.assets]
    # dir = ':resourceDir/_gen'
    dir = ':cacheDir/resources/_gen'
  [caches.images]
    # dir = ':resourceDir/_gen'
    dir = ':cacheDir/resources/_gen'

[Author]
  name = "Simon Heimlicher"
  # NOTE: email is set in data file 'assets/data/claris/en.yaml'
  # email = "user@example.net"

# Allow imaging options to be set in theme config file
[imaging]
  _merge = 'deep'

# Render custom 404 page
# FIXME: does not seem to work for 'hugo server'
# [[redirects]]
#     from   = "/**"
#     to     = "/error/404/"
#     status = 404

[security]
  # Merge security from theme for asset pipeline
  _merge = "deep"
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^babel$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

[permalinks]
    articles = ":sections/:filename"

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

[related]
  includeNewer = true
  threshold = 50
  toLower = true

[[related.indices]]
  name = "categories"
  weight = 100

[[related.indices]]
  name = "tags"
  weight = 100

[[related.indices]]
    name = "keywords"
    weight = 100

[[related.indices]]
  name = "date"
  weight = 10
