minifyOutput: true

disableCSS: true
disableHTML: true
disableJS: true
disableJSON: true
disableSVG: true
disableXML: true

tdewolff:
  css:
    keepCSS2: true
    precision: 0
  html:
    keepComments: true
    keepConditionalComments: true
    keepDefaultAttrVals: true
    keepDocumentTags: true
    keepEndTags: true
    keepQuotes: true
    keepWhitespace: true
  js:
    keepVarNames: true
    noNullishOperator: true
    precision: 0
  json:
    keepNumbers: true
    precision: 0
  svg:
    keepComments: true
    precision: 0
  xml:
    keepWhitespace: true

# Default config from https://gohugo.io/getting-started/configuration/#configure-minify
# disableCSS: false
# disableHTML: false
# disableJS: false
# disableJSON: false
# disableSVG: false
# disableXML: false
# minifyOutput: false
# tdewolff:
#   css:
#     keepCSS2: true
#     precision: 0
#   html:
#     keepComments: false
#     keepConditionalComments: true
#     keepDefaultAttrVals: true
#     keepDocumentTags: true
#     keepEndTags: true
#     keepQuotes: false
#     keepWhitespace: false
#   js:
#     keepVarNames: false
#     noNullishOperator: false
#     precision: 0
#   json:
#     keepNumbers: false
#     precision: 0
#   svg:
#     keepComments: false
#     precision: 0
#   xml:
#     keepWhitespace: false
