# NOTE: It is imperative for `build.buildStats.enable` to be `true`
# in both stage and production, or any environment for which
# `is-build-environment production` returns true
build:
  writeStats: true
  # New from 0.15.0
  buildStats:
    # disableClasses: false
    # disableIDs: false
    # disableTags: false
    enable: true
